name: CI/CD Tienda Perritos - Frontend

on:
  push:
    branches: [ "master" ] # <-- Cambiado de deploy a master

jobs:
  build-push-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    # 1. Configurar credenciales de AWS usando los Secrets que guardamos
    - name: Configurar credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # 2. Login oficial en Amazon ECR
    - name: Login en Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # 3. Build imagen Frontend y push a Amazon ECR
    - name: Build imagen Frontend y push a Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: tienda-frontend # <-- Nombre exacto de tu repo en ECR
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    # 4. Desplegar temporalmente en AWS vía SSH (usando la imagen de ECR)
    - name: Desplegar Frontend en AWS vía SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Logearse en AWS ECR desde la instancia EC2 para que pueda descargar la imagen
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 533368342861.dkr.ecr.us-east-1.amazonaws.com
          
          # Detener y borrar el contenedor viejo
          docker stop tienda-frontend || true
          docker rm tienda-frontend || true
          
          # Descargar la nueva imagen desde tu ECR y correrla
          docker pull 533368342861.dkr.ecr.us-east-1.amazonaws.com/tienda-frontend:latest
          docker run -d --name tienda-frontend -p 80:80 533368342861.dkr.ecr.us-east-1.amazonaws.com/tienda-frontend:latest